### PR TITLE
updates to do backups

### PR DESCRIPTION
**Pull request by afreidah**

### CODE REVIEW

**Comment by afreidah** [comment]
test this please

**Comment by afreidah** [comment]
test this please

**Comment by afreidah** [comment]
test this please

**Comment by afreidah** [comment]
test this please

**Comment by afreidah** [comment]
test this please

**Comment by afreidah** [comment]
test this please

**Comment by smedefind** [comment]
Please squash commits

**Comment by afreidah** [comment]
Ill squash after Jeff reviews.  Got caught up trying to get thor to work last night, actually squashed tons of commits but I forgot a few of the early ones.

**Comment by afreidah** [comment]
test this please

**Comment by afreidah** [comment]
test this please

**Pull request merged**
